plugins:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5.3

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Metrics:
  Enabled: false

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Style/StringLiterals:
  EnforcedStyle: double_quotes
