plugins:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable

# Layout/BeginEndAlignment:
#   EnforcedStyleAlignWith: start_of_line

# Layout/CaseIndentation:
#   EnforcedStyle: end

# Layout/EmptyLineBetweenDefs:
#   AllowAdjacentOneLineDefs: true

# Layout/EndAlignment:
#   EnforcedStyleAlignWith: variable

# Layout/FirstHashElementIndentation:
#   EnforcedStyle: consistent

# Layout/LineLength:
#   Enabled: false

# Layout/SpaceInsideBlockBraces:
#   SpaceBeforeBlockParameters: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Metrics:
  Enabled: false

# Style/AccessorGrouping:
#   Enabled: false

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Style/StringLiterals:
  EnforcedStyle: double_quotes

# Style/YodaCondition:
#   EnforcedStyle: forbid_for_equality_operators_only
