# frozen_string_literal: true

module SPSS
  NUMERIC = 0

  NO_MISSVAL = 0
  ONE_MISSVAL = 1
  TWO_MISSVAL = 2
  THREE_MISSVAL = 3
  MISS_RANGE = -2
  MISS_RANGEANDVAL = -3

  OK = 0

  FILE_OERROR = 1
  FILE_WERROR = 2
  FILE_RERROR = 3
  FITAB_FULL = 4
  INVALID_HANDLE = 5
  INVALID_FILE = 6
  NO_MEMORY = 7

  OPEN_RDMODE = 8
  OPEN_WRMODE = 9

  INVALID_VARNAME = 10
  DICT_EMPTY = 11
  VAR_NOTFOUND = 12
  DUP_VAR = 13
  NUME_EXP = 14
  STR_EXP = 15
  SHORTSTR_EXP = 16
  INVALID_VARTYPE = 17

  INVALID_MISSFOR = 18
  INVALID_COMPSW = 19
  INVALID_PRFOR = 20
  INVALID_WRFOR = 21
  INVALID_DATE = 22
  INVALID_TIME = 23

  NO_VARIABLES = 24
  MIXED_TYPES = 25
  DUP_VALUE = 27

  INVALID_CASEWGT = 28
  INCOMPATIBLE_DICT = 29
  DICT_COMMIT = 30
  DICT_NOTCOMMIT = 31

  NO_TYPE2 = 33
  NO_TYPE73 = 41
  INVALID_DATEINFO = 45
  NO_TYPE999 = 46
  EXC_STRVALUE = 47
  CANNOT_FREE = 48
  BUFFER_SHORT = 49
  INVALID_CASE = 50
  INTERNAL_VLABS = 51
  INCOMPAT_APPEND = 52
  INTERNAL_D_A = 53
  FILE_BADTEMP = 54
  DEW_NOFIRST = 55
  INVALID_MEASURELEVEL = 56
  INVALID_7SUBTYPE = 57
  INVALID_VARHANDLE = 58
  INVALID_ENCODING = 59
  FILES_OPEN = 60

  INVALID_MRSETDEF = 70
  INVALID_MRSETNAME = 71
  DUP_MRSETNAME = 72

  BAD_EXTENSION = 73
  INVALID_EXTENDEDSTRING = 74

  INVALID_ATTRNAME = 75
  INVALID_ATTRDEF = 76
  INVALID_MRSETINDEX = 77
  INVALID_VARSETDEF = 78
  INVALID_ROLE = 79

  INVALID_PASSWORD = 80
  EMPTY_PASSWORD = 81

  EXC_LEN64 = -1
  EXC_LEN120 = -2
  EXC_VARLABEL = -2
  EXC_LEN60 = -4
  EXC_VALLABEL = -4
  FILE_END = -5
  NO_VARSETS = -6
  EMPTY_VARSETS = -7
  NO_LABELS = -8
  NO_LABEL = -9
  NO_CASEWGT = -10
  NO_DATEINFO = -11
  NO_MULTRESP = -12
  EMPTY_MULTRESP = -13
  NO_DEW = -14
  EMPTY_DEW = -15

  FMT_A = 1
  FMT_AHEX = 2
  FMT_COMMA = 3
  FMT_DOLLAR = 4
  FMT_F = 5
  FMT_IB = 6
  FMT_PIBHEX = 7
  FMT_P = 8
  FMT_PIB = 9
  FMT_PK = 10
  FMT_RB = 11
  FMT_RBHEX = 12
  FMT_Z = 15
  FMT_N = 16
  FMT_E = 17
  FMT_DATE = 20
  FMT_TIME = 21
  FMT_DATE_TIME = 22
  FMT_ADATE = 23
  FMT_JDATE = 24
  FMT_DTIME = 25
  FMT_WKDAY = 26
  FMT_MONTH = 27
  FMT_MOYR = 28
  FMT_QYR = 29
  FMT_WKYR = 30
  FMT_PCT = 31
  FMT_DOT = 32
  FMT_CCA = 33
  FMT_CCB = 34
  FMT_CCC = 35
  FMT_CCD = 36
  FMT_CCE = 37
  FMT_EDATE = 38
  FMT_SDATE = 39
  FMT_MTIME = 85
  FMT_YMDHMS = 86

  MLVL_UNK = 0
  MLVL_NOM = 1
  MLVL_ORD = 2
  MLVL_RAT = 3
  MLVL_FLA = 4
  MLVL_TPL = 5

  ALIGN_LEFT = 0
  ALIGN_RIGHT = 1
  ALIGN_CENTER = 2

  ROLE_INPUT = 0
  ROLE_TARGET = 1
  ROLE_BOTH = 2
  ROLE_NONE = 3
  ROLE_PARTITION = 4
  ROLE_SPLIT = 5
  ROLE_FREQUENCY = 6
  ROLE_RECORDID = 7

  NAME_OK = 0
  NAME_SCRATCH = 1
  NAME_SYSTEM = 2
  NAME_BADLTH = 3
  NAME_BADCHAR = 4
  NAME_RESERVED = 5
  NAME_BADFIRST = 6

  MAX_VARNAME = 64
  MAX_SHORTVARNAME = 8
  MAX_SHORTSTRING = 8
  MAX_IDSTRING = 64
  MAX_LONGSTRING = 32_767
  MAX_VALLABEL = 120
  MAX_VARLABEL = 256
  MAX_ENCODING = 64
  MAX_7SUBTYPE = 40
  MAX_PASSWORD = 10

  T7_DOCUMENTS = 0
  T7_VAXDE_DICT = 1
  T7_VAXDE_DATA = 2
  T7_SOURCE = 3
  T7_HARDCONST = 4
  T7_VARSETS = 5
  T7_TRENDS = 6
  T7_MULTRESP = 7
  T7_DEW_DATA = 8
  T7_TEXTSMART = 10
  T7_MSMTLEVEL = 11
  T7_DEW_GUID = 12
  T7_XVARNAMES = 13
  T7_XSTRINGS = 14
  T7_CLEMENTINE = 15
  T7_NCASES = 16
  T7_FILE_ATTR = 17
  T7_VAR_ATTR = 18
  T7_EXTMRSETS = 19
  T7_ENCODING = 20
  T7_LONGSTRLABS = 21
  T7_LONGSTRMVAL = 22
  T7_SORTINDEX = 23

  ENCODING_CODEPAGE = 0
  ENCODING_UTF8 = 1
end
